### ISSUE TITLE
Deprecation warning for Bitcoin depends build on macOS 12.5.1 (Intel Mac)

### ISSUE THREAD

**Issue by Sjors** [chaincodelabs/libmultiprocess#76] opened 2022-09-09 11:45 UTC
```
/Users/sjors/dev/bitcoin/depends/work/build/x86_64-apple-darwin21.6.0/native_libmultiprocess/7d10f3b1e39caa04b3fcddebf720fd3a2b54c21d-6bdf33803cf/src/mp/gen.cpp:166:31: warning: 'parseDiskFile' is deprecated: Use parseFromDirectory() instead. [-Wdeprecated-declarations]
    auto file_schema = parser.parseDiskFile(src_file, src_file, import_paths);
                              ^
/Users/sjors/dev/bitcoin/depends/x86_64-apple-darwin21.6.0/native/include/capnp/schema-parser.h:105:7: note: 'parseDiskFile' has been explicitly marked deprecated here
      CAPNP_DEPRECATED("Use parseFromDirectory() instead.");
      ^
/Users/sjors/dev/bitcoin/depends/x86_64-apple-darwin21.6.0/native/include/capnp/common.h:57:26: note: expanded from macro 'CAPNP_DEPRECATED'
#define CAPNP_DEPRECATED KJ_DEPRECATED
                         ^
/Users/sjors/dev/bitcoin/depends/x86_64-apple-darwin21.6.0/native/include/kj/common.h:186:20: note: expanded from macro 'KJ_DEPRECATED'
    __attribute__((deprecated(reason)))
                   ^
1 warning generated.
```

**Comment by ryanofsky** [comment] 2022-09-13 19:44
Will close just because this is a duplicate of https://github.com/chaincodelabs/libmultiprocess/issues/39. Would be good to fix, it's just a low priority because the code works aside from the deprecation warning.

**Closed by ryanofsky** 2022-09-13 19:44 UTC
